# Feb 1 Note

In [1]:
import numpy as np

In [2]:
whos

Variable   Type      Data/Info
------------------------------
np         module    <module 'numpy' from '/op<...>kages/numpy/__init__.py'>


In [4]:
# rank 1
A = np.array([[1,2], [3,6]])
A

array([[1, 2],
       [3, 6]])

In [6]:
# inverse
np.linalg.inv(A)

array([[-1.80143985e+16,  6.00479950e+15],
       [ 9.00719925e+15, -3.00239975e+15]])

In [7]:
A = np.array([[1,2],[-9,4]])
A

array([[ 1,  2],
       [-9,  4]])

In [8]:
# returns Identity Matrix
np.matmul(A, np.linalg.inv(A))

array([[ 1.00000000e+00, -1.38777878e-17],
       [ 0.00000000e+00,  1.00000000e+00]])