# Feb 3rd Note

In [1]:
import numpy as np

In [2]:
x = np.array([[1,1], [1,3], [1,4], [1,5]])
x

array([[1, 1],
       [1, 3],
       [1, 4],
       [1, 5]])

In [3]:
y = np.array([3,2,5,4])

In [4]:
x.shape

(4, 2)

In [5]:
y.shape

(4,)

In [6]:
y = y.reshape(4,1)
y.shape

(4, 1)

In [7]:
y

array([[3],
       [2],
       [5],
       [4]])

In [8]:
[beta_hat, residuals, rank, s] = np.linalg.lstsq(x, y, rcond=-1)

In [9]:
beta_hat

array([[2.2],
       [0.4]])

In [10]:
residuals

array([3.6])

In [11]:
rank

2

In [12]:
s

array([7.37265882, 0.80243504])