# Jan 29 note

In [5]:
import numpy as np
import pandas as pd

In [2]:
x1 = np.array([ [1,2], [3,4], [1,2] ])
x1

array([[1, 2],
       [3, 4],
       [1, 2]])

In [3]:
x2 = np.array([ [2,1], [6,3] ])
x2

array([[2, 1],
       [6, 3]])

In [4]:
np.matmul(x1, x2)

array([[14,  7],
       [30, 15],
       [14,  7]])

In [6]:
df1 = pd.DataFrame(x1)
df1

0  1
0  1  2
1  3  4
2  1  2

In [8]:
df2 = pd.DataFrame(x2)
df2

0  1
0  2  1
1  6  3

In [9]:
whos

Variable   Type         Data/Info
---------------------------------
df1        DataFrame       0  1\n0  1  2\n1  3  4\n2  1  2
df2        DataFrame       0  1\n0  2  1\n1  6  3
np         module       <module 'numpy' from '/op<...>kages/numpy/__init__.py'>
pd         module       <module 'pandas' from '/o<...>ages/pandas/__init__.py'>
x1         ndarray      3x2: 6 elems, type `int64`, 48 bytes
x2         ndarray      2x2: 4 elems, type `int64`, 32 bytes


In [10]:
np.matmul(df1, df2)

0   1
0  14   7
1  30  15
2  14   7

In [11]:
df1 * df2

0     1
0   2.0   2.0
1  18.0  12.0
2   NaN   NaN

In [12]:
x1

array([[1, 2],
       [3, 4],
       [1, 2]])

In [13]:
# Transpose
x1.T

array([[1, 3, 1],
       [2, 4, 2]])

In [14]:
df1.T

0  1  2
0  1  3  1
1  2  4  2

In [15]:
i2 = np.array([[1,0], [0,1]])
i2

array([[1, 0],
       [0, 1]])

In [16]:
np.matmul(x2, i2)

array([[2, 1],
       [6, 3]])

In [18]:
np.linalg.matrix_rank(x2)

1